import matplotlib.pyplot as plt
import os

def process_number(num):
    sequence = [num]
    
    while num != 1:
        if num % 2 != 0:
            num = num * 3 + 1
        else:
            num = num // 2
        sequence.append(num)
    
    return sequence

def plot_sequence(sequence, num):
    plt.figure(figsize=(10, 6))
    plt.plot(sequence, marker='o', linestyle='-', color='b')
    plt.title(f"Sequence Generated by the Algorithm for Input {num}")
    plt.xlabel("Step")
    plt.ylabel("Value")
    plt.grid(True)
    filename = f"sequence_plot_{num}.png"
    plt.savefig(filename)
    plt.close()  # Close the plot to free memory

def main():
    # Ensure the output directory exists
    output_dir = "plots"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Change the working directory to the output directory
    os.chdir(output_dir)

    for num in range(1, 10):
        sequence = process_number(num)
        plot_sequence(sequence, num)
        print(f"Saved plot for input {num} as sequence_plot_{num}.png")

if __name__ == "__main__":
    main()
